package com.demo.order.service;

import com.demo.order.dto.CreateOrderRequest;
import com.demo.order.dto.OrderEvent;
import com.demo.order.dto.OrderResponse;
import com.demo.order.entity.Order;
import com.demo.order.publisher.OrderEventPublisher;
import com.demo.order.repository.OrderRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * Implementation of OrderService
 * Handles order creation, database persistence, and event publishing
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class OrderServiceImpl implements OrderService {
    
    private final OrderRepository orderRepository;
    private final OrderEventPublisher orderEventPublisher;
    
    /**
     * Create a new order, save to database, and publish event to RabbitMQ
     * Validation is handled by Bean Validation in DTO (@Valid in Controller)
     * Order ID is auto-generated by Entity (@PrePersist)
     * 
     * @param request the order creation request (already validated)
     * @return OrderResponse with order details
     */
    @Override
    @Transactional
    public OrderResponse createOrder(CreateOrderRequest request) {
        log.info("Creating order for customer: {}, amount: {}", 
                request.getCustomerId(), request.getAmount());
        
        // Build and save order - ID auto-generated by @PrePersist
        Order order = Order.builder()
                .customerId(request.getCustomerId())
                .amount(request.getAmount())
                .status("CREATED")
                .build();
        
        order = orderRepository.save(order);
        log.info("Order saved to database: orderId={}", order.getOrderId());
        
        // Publish event to RabbitMQ
        OrderEvent orderEvent = toOrderEvent(order);
        orderEventPublisher.publishOrderCreated(orderEvent);
        
        log.info("Order created successfully: orderId={}", order.getOrderId());
        return toOrderResponse(order);
    }
    
    /**
     * Get order by ID
     * 
     * @param orderId the order identifier
     * @return OrderResponse with order details
     * @throws IllegalArgumentException if order not found
     */
    @Override
    public OrderResponse getOrderById(String orderId) {
        log.info("Fetching order: orderId={}", orderId);
        
        Order order = orderRepository.findById(orderId)
                .orElseThrow(() -> new IllegalArgumentException("Order not found: " + orderId));
        
        return toOrderResponse(order);
    }
    
    /**
     * Get all orders by customer ID
     * 
     * @param customerId the customer identifier
     * @return List of OrderResponse
     */
    @Override
    public List<OrderResponse> getOrdersByCustomerId(String customerId) {
        log.info("Fetching orders for customer: {}", customerId);
        
        return orderRepository.findByCustomerId(customerId).stream()
                .map(this::toOrderResponse)
                .toList();
    }
    
    /**
     * Map Order entity to OrderResponse DTO
     */
    private OrderResponse toOrderResponse(Order order) {
        return new OrderResponse(
            order.getOrderId(),
            order.getCustomerId(),
            order.getAmount(),
            order.getStatus(),
            order.getCreatedAt()
        );
    }
    
    /**
     * Map Order entity to OrderEvent for messaging
     */
    private OrderEvent toOrderEvent(Order order) {
        return new OrderEvent(
            order.getOrderId(),
            order.getCustomerId(),
            order.getAmount(),
            order.getStatus(),
            order.getCreatedAt()
        );
    }
}
