apiVersion: v1
kind: Secret
metadata:
  name: order-service-secrets
type: Opaque
stringData:
  db.username: "postgres"
  db.password: "postgres123"
  rabbitmq.username: "admin"
  rabbitmq.password: "admin123"
