apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  db.host: "postgres-service"
  db.port: "5432"
  db.name: "orders_db"
  rabbitmq.host: "rabbitmq-service"
  rabbitmq.port: "5672"
