{{- if .Values.notificationService.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secrets
  labels:
    app: notification-service
type: Opaque
stringData:
  rabbitmq.username: {{ .Values.secrets.rabbitmq.username | quote }}
  rabbitmq.password: {{ .Values.secrets.rabbitmq.password | quote }}
{{- end }}
