{{- if .Values.orderService.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secrets
  labels:
    app: order-service
type: Opaque
stringData:
  db.username: {{ .Values.secrets.postgres.username | quote }}
  db.password: {{ .Values.secrets.postgres.password | quote }}
  rabbitmq.username: {{ .Values.secrets.rabbitmq.username | quote }}
  rabbitmq.password: {{ .Values.secrets.rabbitmq.password | quote }}
{{- end }}
