{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  labels:
    app: postgres
type: Opaque
stringData:
  username: {{ .Values.secrets.postgres.username | quote }}
  password: {{ .Values.secrets.postgres.password | quote }}
{{- end }}
