{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  labels:
    app: rabbitmq
type: Opaque
stringData:
  username: {{ .Values.secrets.rabbitmq.username | quote }}
  password: {{ .Values.secrets.rabbitmq.password | quote }}
{{- end }}
